#!/bin/sh
# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	gi="git init" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	c="code" \
	cde="code ." \
	zt="zathura"

alias \
	cnp="commitandpush" \
	dp="dotfilespush" \
	st="speedtest" \
	up="topgrade ; date" \
	vs="v -O" \
	sp="v -o" \
	ssr="scriptvim" \
	lzd="lazydocker" \
	uptime="uptime -p" \
	fm="fzf-make" \
	fr="fzf-make repeat" \
	fh="fzf-make history" \
	dailies="c /keybase/private/biehlerj/Documents/dailies.md"	
